### ISSUE TITLE
Heroku Setup

### ISSUE THREAD

**Issue by cobracobracobra** [neistow/battlesnake-starter-csharp#1]
How would one use Heroku to host the server instead of Azure?

**Comment by neistow** [comment]
Heroku doesn't officially support a .NET. More about it [here](https://help.heroku.com/PAT3YEDU/does-heroku-support-net-applications). But I guess there are a few ways to deploy an app. Azure still seems fast, native and more convenient way for deploying .net app.

**Comment by cobracobracobra** [comment]
I'm trying to use [a buildpack for dotnet core](https://github.com/jincod/dotnetcore-buildpack), but I'm having trouble figuring out how to work with the API. What files would I need to edit?

I'm avoiding Azure because it has a price tag.

EDIT: I'm largely new to Heroku and servers in general.

**Comment by neistow** [comment]
I haven't deployed languages that are not native for heroku, so I guess I can't help you with that process.

About azure: it's free if you verify your [student status](https://azure.microsoft.com/en-us/free/students/)

**Comment by cobracobracobra** [comment]
I'll use Azure then.

Thanks for the help!
